export const LOADING = "LOADING";
export const LOADING_COMPLETE = "LOADING_COMPLETE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"; 
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_COMPLETE = "REGISTER_COMPLETE";
export const REGISTER_ERROR = "REGISTER_ERROR";
